name: release_helper
description: A helper CLI tool for release-pub AI skill.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0 # Always specify the latest stable version

dependencies:
  args: ^2.5.0
  mason_logger: ^0.2.16
  pub_semver: ^2.1.4
  yaml_edit: ^2.2.0

dev_dependencies:
  pedantic_mono: any
  test: ^1.24.0
